services:
  - type: web
    name: sleep-disorder-app
    env: python
    # ... other settings like buildCommand, startCommand ...

    envVars:
  - key: SECRET_KEY
    generateValue: true
  - key: DATABASE_URL
    fromDatabase:
      name: your-render-postgres-db-name # <<< REPLACE with your actual Render DB name
      property: connectionString
  - key: DJANGO_DEBUG
    value: "False"
  - key: WEB_CONCURRENCY
    value: "4"